---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-eks-gitops
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-eks-gitops
    spec:
      containers:
      - name: aws-eks-gitops
        image: 202624756631.dkr.ecr.us-west-2.amazonaws.com/eks-gitops:6b7e39883c5abd2264877c02b8cb1b0ca6933106
        # image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
